In [90]:
import numpy as np
import time

random_generator = np.random.default_rng()

def generate_data(n_features, n_values):
    features = random_generator.random((n_features, n_values))
    targets = random_generator.random((n_features))
    return features, targets


trainX, trainY = generate_data(5000, 4)
testX, testY = generate_data(5, 4)

In [91]:
print('trainX.shape', trainX.shape)
print('trainY.shape', trainY.shape)

trainX.shape (5000, 4)
trainY.shape (5000,)


In [101]:
class RNN:
    def __init__(self):
        self.global_weight = [1, 1] # [Input, Recurrent Weight]
        self.local_weight = [0.001, 0.001]
        self.W_sign = [0, 0]

        self.eta_p = 1.2
        self.eta_n = 0.5

    def state_handler(self, input_x, previous_state):
        return input_x * self.global_weight[0] + previous_state * self.global_weight[1]

    def forward_propagation(self, X):
      # Computes the forward propagation of the RNN.
      S = np.zeros((X.shape[0], X.shape[1]+1))
      for k in range(0, X.shape[1]):
          next_state = self.state_handler(X[:,k], S[:,k])
          S[:,k+1] = next_state
      return S

    def backward_propagation(self, X, S, grad_out):
      # Computes the backward propagation of the RNN.
        grad_over_time = np.zeros(( X.shape[0], X.shape[1]+1 ))
        grad_over_time[:,-1] = grad_out

        wx_grad = 0
        wy_grad = 0
        for k in range(X.shape[1], 0, -1):
            wx_grad += np.sum( grad_over_time[:, k] * X[:, k-1] )
            wy_grad += np.sum( grad_over_time[:, k] * S[:, k-1] )

            grad_over_time[:, k-1] = grad_over_time[:, k] * self.global_weight[1]
        return (wx_grad, wy_grad), grad_over_time

    def update_rprop(self, X, Y, W_prev_sign, local_weight):
        S = self.forward_propagation(X)
        grad_out = 2 * (S[:, -1] - Y) / 500
        print(sum(grad_out))
        W_grads, _ = self.backward_propagation(X, S, grad_out)
#         print(W_grads)
        self.W_sign = np.sign(W_grads)

        for i, _ in enumerate(self.global_weight):
            if self.W_sign[i] == W_prev_sign[i]:
                local_weight[i] *= self.eta_p
            else:
                local_weight[i] *= self.eta_n
        self.local_weight = local_weight

    def train(self, X, Y, training_epochs):
        for epochs in range(training_epochs):
            print( self.W_sign, self.local_weight, self.global_weight)
            self.update_rprop(X, Y, self.W_sign, self.local_weight)

            for i, _ in enumerate(self.global_weight):
                if i == 0:
                    self.global_weight[i] -= self.W_sign[i] * self.local_weight[i]


In [102]:
rnn = RNN()
rnn.train(trainX, trainY, 200)

print (f"Targets are: {testY}")
y = rnn.forward_propagation(testX)[:, -1]
print (f"Predicted are: {y}")

[0, 0] [0.001, 0.001] [1, 1]
29.974425766225448
[1. 1.] [0.0005, 0.0005] [0.9995, 1]
29.954376321006716
[1. 1.] [0.0006, 0.0006] [0.9989, 1]
29.9303169867441
[1. 1.] [0.0007199999999999999, 0.0007199999999999999] [0.99818, 1]
29.90144578562907
[1. 1.] [0.0008639999999999999, 0.0008639999999999999] [0.997316, 1]
29.866800344291146
[1. 1.] [0.0010367999999999998, 0.0010367999999999998] [0.9962792, 1]
29.825225814685393
[1. 1.] [0.0012441599999999998, 0.0012441599999999998] [0.99503504, 1]
29.775336379158684
[1. 1.] [0.0014929919999999996, 0.0014929919999999996] [0.993542048, 1]
29.715469056526512
[1. 1.] [0.0017915903999999995, 0.0017915903999999995] [0.9917504576, 1]
29.643628269368048
[1. 1.] [0.0021499084799999992, 0.0021499084799999992] [0.9896005491200001, 1]
29.55741932477765
[1. 1.] [0.002579890175999999, 0.002579890175999999] [0.987020658944, 1]
29.453968591269344
[1. 1.] [0.0030958682111999988, 0.0030958682111999988] [0.9839247907328, 1]
29.32982771105938
[1. 1.] [0.003715041853

In [36]:
global_weight = [1, 1] 

In [37]:
def state_handler(input_x, previous_state):
        return input_x * global_weight[0] + previous_state * global_weight[1]

In [38]:
X = trainX
S = np.zeros((X.shape[0], X.shape[1]+1))

In [39]:
for k in range(0, X.shape[1]):
  next_state = state_handler(X[:,k], S[:,k])
  S[:,k+1] = next_state

In [17]:
S.shape

(5000, 5)

In [25]:
trainX.shape

(5000, 4)

In [ ]:
def state_handler(self, input_x, previous_state):
        return input_x * self.global_weight[0] + previous_state * self.global_weight[1]

In [20]:
S[:,0]*[1, 1][1] 

array([0., 0., 0., ..., 0., 0., 0.])

In [22]:
S[:,0].shape

(5000,)

In [23]:
[1, 1][1] 

1

In [41]:
Y = trainY

In [42]:
grad_out = 2 * (S[:, -1] - Y) / 500

In [46]:
grad_out

array([0.00767497, 0.00261783, 0.00379138, ..., 0.00989653, 0.00303773,
       0.00935126])

In [47]:
grad_over_time = np.zeros(( X.shape[0], X.shape[1]+1 ))
grad_over_time[:,-1] = grad_out

In [54]:
S

array([[0.        , 0.31432279, 0.44660938, 1.37835905, 2.19350278],
       [0.        , 0.4668691 , 0.60265939, 1.42648053, 1.54897401],
       [0.        , 0.62458618, 1.16765573, 1.4902387 , 1.63806539],
       ...,
       [0.        , 0.9532179 , 1.5233587 , 2.16728477, 2.58377996],
       [0.        , 0.52922652, 0.68950846, 0.90395224, 1.40365043],
       [0.        , 0.15516796, 1.07445864, 1.94538891, 2.56130436]])

In [48]:
grad_over_time

array([[0.        , 0.        , 0.        , 0.        , 0.00767497],
       [0.        , 0.        , 0.        , 0.        , 0.00261783],
       [0.        , 0.        , 0.        , 0.        , 0.00379138],
       ...,
       [0.        , 0.        , 0.        , 0.        , 0.00989653],
       [0.        , 0.        , 0.        , 0.        , 0.00303773],
       [0.        , 0.        , 0.        , 0.        , 0.00935126]])

In [59]:
wx_grad = 0
wy_grad = 0
for k in range(X.shape[1], 0, -1):
    wx_grad += np.sum( grad_over_time[:, k] * X[:, k-1] )
    wy_grad += np.sum( grad_over_time[:, k] * S[:, k-1] )
    grad_over_time[:, k-1] = grad_over_time[:, k] * 1

In [60]:
wx_grad

66.83205762883043

In [61]:
wy_grad

100.40356368735185

In [62]:
grad_over_time

array([[0.00767497, 0.00767497, 0.00767497, 0.00767497, 0.00767497],
       [0.00261783, 0.00261783, 0.00261783, 0.00261783, 0.00261783],
       [0.00379138, 0.00379138, 0.00379138, 0.00379138, 0.00379138],
       ...,
       [0.00989653, 0.00989653, 0.00989653, 0.00989653, 0.00989653],
       [0.00303773, 0.00303773, 0.00303773, 0.00303773, 0.00303773],
       [0.00935126, 0.00935126, 0.00935126, 0.00935126, 0.00935126]])

In [64]:
W_grads = (wx_grad, wy_grad)

In [66]:
W_sign = np.sign(W_grads)

In [69]:
W_sign

array([1., 1.])

In [72]:
global_weight
W_prev_sign = [0, 0]
local_weight = [0.001, 0.001]
eta_p = 1.2
eta_n = 0.5

In [73]:
for i, _ in enumerate(global_weight):
    if W_sign[i] == W_prev_sign[i]:
        local_weight[i] *= eta_p
    else:
        local_weight[i] *= eta_n
local_weight = local_weight

In [75]:
W_sign

array([1., 1.])

In [74]:
local_weight

[0.0005, 0.0005]

In [76]:
for i, _ in enumerate(global_weight):
        global_weight[i] -= W_sign[i] * local_weight[i]

In [77]:
global_weight

[0.9995, 0.9995]

In [78]:
W_sign

array([1., 1.])

In [79]:
local_weight

[0.0005, 0.0005]

In [52]:
 grad_over_time[:, 4]*X[:, 4-1]

array([0.0062562 , 0.00032067, 0.00056047, ..., 0.00412186, 0.00151795,
       0.00575958])

array([0.81514372, 0.12249348, 0.14782669, ..., 0.41649519, 0.49969818,
       0.61591545])

In [53]:
np.array([1,2,3])*np.array([1,2,3])

array([1, 4, 9])